version: "3"

services:
  xk:
    image: exekube/exekube:0.3.2-aws
    working_dir: /project
    environment:
      USER: root
      ENV: ${ENV:?err}


      TF_INPUT: "0"
      TF_LOG:
      TF_VAR_aws_region: us-west-2
      TF_VAR_cluster_name: eks-experimental-ilya
      # TF_VAR_serviceaccount_key: /project/live/${ENV}/secrets/kube-system/owner.json

      TF_VAR_default_dir: /project/live/${ENV}/k8s
      TF_VAR_secrets_dir: /project/live/${ENV}/secrets

    ports:
      - 8001:8001
    volumes:
      - .:/project
      - ./.config/${ENV}/aws:/root/.aws
      - ./.config/${ENV}/helm:/root/.helm
      - ./.config/${ENV}/terragrunt:/root/.terragrunt
      - ./.config/${ENV}/kube:/root/.kube

      # EXEKUBE DEVELOPMENT
      - ../../exekube/modules:/exekube-modules
      # ---
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
