---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for storing Terraform state
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: eks-experimental-ilya-tfstate-dev
